// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspnetcore.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_aspnetcore_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_aspnetcore_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3010000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3010000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/wrappers.pb.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_aspnetcore_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_aspnetcore_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_aspnetcore_2eproto;
namespace aspnet {
namespace core {
class MvcRoute;
class MvcRouteDefaultTypeInternal;
extern MvcRouteDefaultTypeInternal _MvcRoute_default_instance_;
}  // namespace core
}  // namespace aspnet
PROTOBUF_NAMESPACE_OPEN
template<> ::aspnet::core::MvcRoute* Arena::CreateMaybeMessage<::aspnet::core::MvcRoute>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace aspnet {
namespace core {

enum HttpMethod : int {
  HttpMethod_Get = 0,
  HttpMethod_Post = 1,
  HttpMethod_Put = 2,
  HttpMethod_Delete = 3,
  HttpMethod_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  HttpMethod_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool HttpMethod_IsValid(int value);
constexpr HttpMethod HttpMethod_MIN = HttpMethod_Get;
constexpr HttpMethod HttpMethod_MAX = HttpMethod_Delete;
constexpr int HttpMethod_ARRAYSIZE = HttpMethod_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* HttpMethod_descriptor();
template<typename T>
inline const std::string& HttpMethod_Name(T enum_t_value) {
  static_assert(::std::is_same<T, HttpMethod>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function HttpMethod_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    HttpMethod_descriptor(), enum_t_value);
}
inline bool HttpMethod_Parse(
    const std::string& name, HttpMethod* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<HttpMethod>(
    HttpMethod_descriptor(), name, value);
}
enum HttpInputSource : int {
  HttpInputSource_Unspecified = 0,
  HttpInputSource_Body = 1,
  HttpInputSource_Form = 2,
  HttpInputSource_Query = 3,
  HttpInputSource_Header = 4,
  HttpInputSource_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  HttpInputSource_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool HttpInputSource_IsValid(int value);
constexpr HttpInputSource HttpInputSource_MIN = HttpInputSource_Unspecified;
constexpr HttpInputSource HttpInputSource_MAX = HttpInputSource_Header;
constexpr int HttpInputSource_ARRAYSIZE = HttpInputSource_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* HttpInputSource_descriptor();
template<typename T>
inline const std::string& HttpInputSource_Name(T enum_t_value) {
  static_assert(::std::is_same<T, HttpInputSource>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function HttpInputSource_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    HttpInputSource_descriptor(), enum_t_value);
}
inline bool HttpInputSource_Parse(
    const std::string& name, HttpInputSource* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<HttpInputSource>(
    HttpInputSource_descriptor(), name, value);
}
// ===================================================================

class MvcRoute :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aspnet.core.MvcRoute) */ {
 public:
  MvcRoute();
  virtual ~MvcRoute();

  MvcRoute(const MvcRoute& from);
  MvcRoute(MvcRoute&& from) noexcept
    : MvcRoute() {
    *this = ::std::move(from);
  }

  inline MvcRoute& operator=(const MvcRoute& from) {
    CopyFrom(from);
    return *this;
  }
  inline MvcRoute& operator=(MvcRoute&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MvcRoute& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MvcRoute* internal_default_instance() {
    return reinterpret_cast<const MvcRoute*>(
               &_MvcRoute_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MvcRoute& a, MvcRoute& b) {
    a.Swap(&b);
  }
  inline void Swap(MvcRoute* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MvcRoute* New() const final {
    return CreateMaybeMessage<MvcRoute>(nullptr);
  }

  MvcRoute* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MvcRoute>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MvcRoute& from);
  void MergeFrom(const MvcRoute& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MvcRoute* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aspnet.core.MvcRoute";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_aspnetcore_2eproto);
    return ::descriptor_table_aspnetcore_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCustomMethodAttributesFieldNumber = 4,
    kCustomMethodBodyInlineFieldNumber = 7,
    kCustomExceptionHandlingFieldNumber = 9,
    kCustomMethodBodyTemplateFieldNumber = 6,
    kRoutePatternFieldNumber = 3,
    kCustomReturnTypeFieldNumber = 5,
    kMethodFieldNumber = 1,
    kSourceFieldNumber = 2,
    kIsEmptyRequestFieldNumber = 8,
  };
  // repeated string custom_method_attributes = 4;
  int custom_method_attributes_size() const;
  private:
  int _internal_custom_method_attributes_size() const;
  public:
  void clear_custom_method_attributes();
  const std::string& custom_method_attributes(int index) const;
  std::string* mutable_custom_method_attributes(int index);
  void set_custom_method_attributes(int index, const std::string& value);
  void set_custom_method_attributes(int index, std::string&& value);
  void set_custom_method_attributes(int index, const char* value);
  void set_custom_method_attributes(int index, const char* value, size_t size);
  std::string* add_custom_method_attributes();
  void add_custom_method_attributes(const std::string& value);
  void add_custom_method_attributes(std::string&& value);
  void add_custom_method_attributes(const char* value);
  void add_custom_method_attributes(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& custom_method_attributes() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_custom_method_attributes();
  private:
  const std::string& _internal_custom_method_attributes(int index) const;
  std::string* _internal_add_custom_method_attributes();
  public:

  // repeated string custom_method_body_inline = 7;
  int custom_method_body_inline_size() const;
  private:
  int _internal_custom_method_body_inline_size() const;
  public:
  void clear_custom_method_body_inline();
  const std::string& custom_method_body_inline(int index) const;
  std::string* mutable_custom_method_body_inline(int index);
  void set_custom_method_body_inline(int index, const std::string& value);
  void set_custom_method_body_inline(int index, std::string&& value);
  void set_custom_method_body_inline(int index, const char* value);
  void set_custom_method_body_inline(int index, const char* value, size_t size);
  std::string* add_custom_method_body_inline();
  void add_custom_method_body_inline(const std::string& value);
  void add_custom_method_body_inline(std::string&& value);
  void add_custom_method_body_inline(const char* value);
  void add_custom_method_body_inline(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& custom_method_body_inline() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_custom_method_body_inline();
  private:
  const std::string& _internal_custom_method_body_inline(int index) const;
  std::string* _internal_add_custom_method_body_inline();
  public:

  // repeated string custom_exception_handling = 9;
  int custom_exception_handling_size() const;
  private:
  int _internal_custom_exception_handling_size() const;
  public:
  void clear_custom_exception_handling();
  const std::string& custom_exception_handling(int index) const;
  std::string* mutable_custom_exception_handling(int index);
  void set_custom_exception_handling(int index, const std::string& value);
  void set_custom_exception_handling(int index, std::string&& value);
  void set_custom_exception_handling(int index, const char* value);
  void set_custom_exception_handling(int index, const char* value, size_t size);
  std::string* add_custom_exception_handling();
  void add_custom_exception_handling(const std::string& value);
  void add_custom_exception_handling(std::string&& value);
  void add_custom_exception_handling(const char* value);
  void add_custom_exception_handling(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& custom_exception_handling() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_custom_exception_handling();
  private:
  const std::string& _internal_custom_exception_handling(int index) const;
  std::string* _internal_add_custom_exception_handling();
  public:

  // string custom_method_body_template = 6;
  void clear_custom_method_body_template();
  const std::string& custom_method_body_template() const;
  void set_custom_method_body_template(const std::string& value);
  void set_custom_method_body_template(std::string&& value);
  void set_custom_method_body_template(const char* value);
  void set_custom_method_body_template(const char* value, size_t size);
  std::string* mutable_custom_method_body_template();
  std::string* release_custom_method_body_template();
  void set_allocated_custom_method_body_template(std::string* custom_method_body_template);
  private:
  const std::string& _internal_custom_method_body_template() const;
  void _internal_set_custom_method_body_template(const std::string& value);
  std::string* _internal_mutable_custom_method_body_template();
  public:

  // .google.protobuf.StringValue route_pattern = 3;
  bool has_route_pattern() const;
  private:
  bool _internal_has_route_pattern() const;
  public:
  void clear_route_pattern();
  const PROTOBUF_NAMESPACE_ID::StringValue& route_pattern() const;
  PROTOBUF_NAMESPACE_ID::StringValue* release_route_pattern();
  PROTOBUF_NAMESPACE_ID::StringValue* mutable_route_pattern();
  void set_allocated_route_pattern(PROTOBUF_NAMESPACE_ID::StringValue* route_pattern);
  private:
  const PROTOBUF_NAMESPACE_ID::StringValue& _internal_route_pattern() const;
  PROTOBUF_NAMESPACE_ID::StringValue* _internal_mutable_route_pattern();
  public:

  // .google.protobuf.StringValue custom_return_type = 5;
  bool has_custom_return_type() const;
  private:
  bool _internal_has_custom_return_type() const;
  public:
  void clear_custom_return_type();
  const PROTOBUF_NAMESPACE_ID::StringValue& custom_return_type() const;
  PROTOBUF_NAMESPACE_ID::StringValue* release_custom_return_type();
  PROTOBUF_NAMESPACE_ID::StringValue* mutable_custom_return_type();
  void set_allocated_custom_return_type(PROTOBUF_NAMESPACE_ID::StringValue* custom_return_type);
  private:
  const PROTOBUF_NAMESPACE_ID::StringValue& _internal_custom_return_type() const;
  PROTOBUF_NAMESPACE_ID::StringValue* _internal_mutable_custom_return_type();
  public:

  // .aspnet.core.HttpMethod method = 1;
  void clear_method();
  ::aspnet::core::HttpMethod method() const;
  void set_method(::aspnet::core::HttpMethod value);
  private:
  ::aspnet::core::HttpMethod _internal_method() const;
  void _internal_set_method(::aspnet::core::HttpMethod value);
  public:

  // .aspnet.core.HttpInputSource source = 2;
  void clear_source();
  ::aspnet::core::HttpInputSource source() const;
  void set_source(::aspnet::core::HttpInputSource value);
  private:
  ::aspnet::core::HttpInputSource _internal_source() const;
  void _internal_set_source(::aspnet::core::HttpInputSource value);
  public:

  // bool is_empty_request = 8;
  void clear_is_empty_request();
  bool is_empty_request() const;
  void set_is_empty_request(bool value);
  private:
  bool _internal_is_empty_request() const;
  void _internal_set_is_empty_request(bool value);
  public:

  // @@protoc_insertion_point(class_scope:aspnet.core.MvcRoute)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> custom_method_attributes_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> custom_method_body_inline_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> custom_exception_handling_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr custom_method_body_template_;
  PROTOBUF_NAMESPACE_ID::StringValue* route_pattern_;
  PROTOBUF_NAMESPACE_ID::StringValue* custom_return_type_;
  int method_;
  int source_;
  bool is_empty_request_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_aspnetcore_2eproto;
};
// ===================================================================

static const int kApiFieldNumber = 25898343;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::aspnet::core::MvcRoute >, 11, false >
  api;

// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MvcRoute

// .aspnet.core.HttpMethod method = 1;
inline void MvcRoute::clear_method() {
  method_ = 0;
}
inline ::aspnet::core::HttpMethod MvcRoute::_internal_method() const {
  return static_cast< ::aspnet::core::HttpMethod >(method_);
}
inline ::aspnet::core::HttpMethod MvcRoute::method() const {
  // @@protoc_insertion_point(field_get:aspnet.core.MvcRoute.method)
  return _internal_method();
}
inline void MvcRoute::_internal_set_method(::aspnet::core::HttpMethod value) {
  
  method_ = value;
}
inline void MvcRoute::set_method(::aspnet::core::HttpMethod value) {
  _internal_set_method(value);
  // @@protoc_insertion_point(field_set:aspnet.core.MvcRoute.method)
}

// .aspnet.core.HttpInputSource source = 2;
inline void MvcRoute::clear_source() {
  source_ = 0;
}
inline ::aspnet::core::HttpInputSource MvcRoute::_internal_source() const {
  return static_cast< ::aspnet::core::HttpInputSource >(source_);
}
inline ::aspnet::core::HttpInputSource MvcRoute::source() const {
  // @@protoc_insertion_point(field_get:aspnet.core.MvcRoute.source)
  return _internal_source();
}
inline void MvcRoute::_internal_set_source(::aspnet::core::HttpInputSource value) {
  
  source_ = value;
}
inline void MvcRoute::set_source(::aspnet::core::HttpInputSource value) {
  _internal_set_source(value);
  // @@protoc_insertion_point(field_set:aspnet.core.MvcRoute.source)
}

// .google.protobuf.StringValue route_pattern = 3;
inline bool MvcRoute::_internal_has_route_pattern() const {
  return this != internal_default_instance() && route_pattern_ != nullptr;
}
inline bool MvcRoute::has_route_pattern() const {
  return _internal_has_route_pattern();
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& MvcRoute::_internal_route_pattern() const {
  const PROTOBUF_NAMESPACE_ID::StringValue* p = route_pattern_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::StringValue*>(
      &PROTOBUF_NAMESPACE_ID::_StringValue_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& MvcRoute::route_pattern() const {
  // @@protoc_insertion_point(field_get:aspnet.core.MvcRoute.route_pattern)
  return _internal_route_pattern();
}
inline PROTOBUF_NAMESPACE_ID::StringValue* MvcRoute::release_route_pattern() {
  // @@protoc_insertion_point(field_release:aspnet.core.MvcRoute.route_pattern)
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = route_pattern_;
  route_pattern_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* MvcRoute::_internal_mutable_route_pattern() {
  
  if (route_pattern_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::StringValue>(GetArenaNoVirtual());
    route_pattern_ = p;
  }
  return route_pattern_;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* MvcRoute::mutable_route_pattern() {
  // @@protoc_insertion_point(field_mutable:aspnet.core.MvcRoute.route_pattern)
  return _internal_mutable_route_pattern();
}
inline void MvcRoute::set_allocated_route_pattern(PROTOBUF_NAMESPACE_ID::StringValue* route_pattern) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(route_pattern_);
  }
  if (route_pattern) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(route_pattern)->GetArena();
    if (message_arena != submessage_arena) {
      route_pattern = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, route_pattern, submessage_arena);
    }
    
  } else {
    
  }
  route_pattern_ = route_pattern;
  // @@protoc_insertion_point(field_set_allocated:aspnet.core.MvcRoute.route_pattern)
}

// repeated string custom_method_attributes = 4;
inline int MvcRoute::_internal_custom_method_attributes_size() const {
  return custom_method_attributes_.size();
}
inline int MvcRoute::custom_method_attributes_size() const {
  return _internal_custom_method_attributes_size();
}
inline void MvcRoute::clear_custom_method_attributes() {
  custom_method_attributes_.Clear();
}
inline std::string* MvcRoute::add_custom_method_attributes() {
  // @@protoc_insertion_point(field_add_mutable:aspnet.core.MvcRoute.custom_method_attributes)
  return _internal_add_custom_method_attributes();
}
inline const std::string& MvcRoute::_internal_custom_method_attributes(int index) const {
  return custom_method_attributes_.Get(index);
}
inline const std::string& MvcRoute::custom_method_attributes(int index) const {
  // @@protoc_insertion_point(field_get:aspnet.core.MvcRoute.custom_method_attributes)
  return _internal_custom_method_attributes(index);
}
inline std::string* MvcRoute::mutable_custom_method_attributes(int index) {
  // @@protoc_insertion_point(field_mutable:aspnet.core.MvcRoute.custom_method_attributes)
  return custom_method_attributes_.Mutable(index);
}
inline void MvcRoute::set_custom_method_attributes(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:aspnet.core.MvcRoute.custom_method_attributes)
  custom_method_attributes_.Mutable(index)->assign(value);
}
inline void MvcRoute::set_custom_method_attributes(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:aspnet.core.MvcRoute.custom_method_attributes)
  custom_method_attributes_.Mutable(index)->assign(std::move(value));
}
inline void MvcRoute::set_custom_method_attributes(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  custom_method_attributes_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:aspnet.core.MvcRoute.custom_method_attributes)
}
inline void MvcRoute::set_custom_method_attributes(int index, const char* value, size_t size) {
  custom_method_attributes_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:aspnet.core.MvcRoute.custom_method_attributes)
}
inline std::string* MvcRoute::_internal_add_custom_method_attributes() {
  return custom_method_attributes_.Add();
}
inline void MvcRoute::add_custom_method_attributes(const std::string& value) {
  custom_method_attributes_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:aspnet.core.MvcRoute.custom_method_attributes)
}
inline void MvcRoute::add_custom_method_attributes(std::string&& value) {
  custom_method_attributes_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:aspnet.core.MvcRoute.custom_method_attributes)
}
inline void MvcRoute::add_custom_method_attributes(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  custom_method_attributes_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:aspnet.core.MvcRoute.custom_method_attributes)
}
inline void MvcRoute::add_custom_method_attributes(const char* value, size_t size) {
  custom_method_attributes_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:aspnet.core.MvcRoute.custom_method_attributes)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
MvcRoute::custom_method_attributes() const {
  // @@protoc_insertion_point(field_list:aspnet.core.MvcRoute.custom_method_attributes)
  return custom_method_attributes_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
MvcRoute::mutable_custom_method_attributes() {
  // @@protoc_insertion_point(field_mutable_list:aspnet.core.MvcRoute.custom_method_attributes)
  return &custom_method_attributes_;
}

// .google.protobuf.StringValue custom_return_type = 5;
inline bool MvcRoute::_internal_has_custom_return_type() const {
  return this != internal_default_instance() && custom_return_type_ != nullptr;
}
inline bool MvcRoute::has_custom_return_type() const {
  return _internal_has_custom_return_type();
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& MvcRoute::_internal_custom_return_type() const {
  const PROTOBUF_NAMESPACE_ID::StringValue* p = custom_return_type_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::StringValue*>(
      &PROTOBUF_NAMESPACE_ID::_StringValue_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::StringValue& MvcRoute::custom_return_type() const {
  // @@protoc_insertion_point(field_get:aspnet.core.MvcRoute.custom_return_type)
  return _internal_custom_return_type();
}
inline PROTOBUF_NAMESPACE_ID::StringValue* MvcRoute::release_custom_return_type() {
  // @@protoc_insertion_point(field_release:aspnet.core.MvcRoute.custom_return_type)
  
  PROTOBUF_NAMESPACE_ID::StringValue* temp = custom_return_type_;
  custom_return_type_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* MvcRoute::_internal_mutable_custom_return_type() {
  
  if (custom_return_type_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::StringValue>(GetArenaNoVirtual());
    custom_return_type_ = p;
  }
  return custom_return_type_;
}
inline PROTOBUF_NAMESPACE_ID::StringValue* MvcRoute::mutable_custom_return_type() {
  // @@protoc_insertion_point(field_mutable:aspnet.core.MvcRoute.custom_return_type)
  return _internal_mutable_custom_return_type();
}
inline void MvcRoute::set_allocated_custom_return_type(PROTOBUF_NAMESPACE_ID::StringValue* custom_return_type) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(custom_return_type_);
  }
  if (custom_return_type) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(custom_return_type)->GetArena();
    if (message_arena != submessage_arena) {
      custom_return_type = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, custom_return_type, submessage_arena);
    }
    
  } else {
    
  }
  custom_return_type_ = custom_return_type;
  // @@protoc_insertion_point(field_set_allocated:aspnet.core.MvcRoute.custom_return_type)
}

// string custom_method_body_template = 6;
inline void MvcRoute::clear_custom_method_body_template() {
  custom_method_body_template_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& MvcRoute::custom_method_body_template() const {
  // @@protoc_insertion_point(field_get:aspnet.core.MvcRoute.custom_method_body_template)
  return _internal_custom_method_body_template();
}
inline void MvcRoute::set_custom_method_body_template(const std::string& value) {
  _internal_set_custom_method_body_template(value);
  // @@protoc_insertion_point(field_set:aspnet.core.MvcRoute.custom_method_body_template)
}
inline std::string* MvcRoute::mutable_custom_method_body_template() {
  // @@protoc_insertion_point(field_mutable:aspnet.core.MvcRoute.custom_method_body_template)
  return _internal_mutable_custom_method_body_template();
}
inline const std::string& MvcRoute::_internal_custom_method_body_template() const {
  return custom_method_body_template_.GetNoArena();
}
inline void MvcRoute::_internal_set_custom_method_body_template(const std::string& value) {
  
  custom_method_body_template_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void MvcRoute::set_custom_method_body_template(std::string&& value) {
  
  custom_method_body_template_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:aspnet.core.MvcRoute.custom_method_body_template)
}
inline void MvcRoute::set_custom_method_body_template(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  custom_method_body_template_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:aspnet.core.MvcRoute.custom_method_body_template)
}
inline void MvcRoute::set_custom_method_body_template(const char* value, size_t size) {
  
  custom_method_body_template_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:aspnet.core.MvcRoute.custom_method_body_template)
}
inline std::string* MvcRoute::_internal_mutable_custom_method_body_template() {
  
  return custom_method_body_template_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* MvcRoute::release_custom_method_body_template() {
  // @@protoc_insertion_point(field_release:aspnet.core.MvcRoute.custom_method_body_template)
  
  return custom_method_body_template_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void MvcRoute::set_allocated_custom_method_body_template(std::string* custom_method_body_template) {
  if (custom_method_body_template != nullptr) {
    
  } else {
    
  }
  custom_method_body_template_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), custom_method_body_template);
  // @@protoc_insertion_point(field_set_allocated:aspnet.core.MvcRoute.custom_method_body_template)
}

// repeated string custom_method_body_inline = 7;
inline int MvcRoute::_internal_custom_method_body_inline_size() const {
  return custom_method_body_inline_.size();
}
inline int MvcRoute::custom_method_body_inline_size() const {
  return _internal_custom_method_body_inline_size();
}
inline void MvcRoute::clear_custom_method_body_inline() {
  custom_method_body_inline_.Clear();
}
inline std::string* MvcRoute::add_custom_method_body_inline() {
  // @@protoc_insertion_point(field_add_mutable:aspnet.core.MvcRoute.custom_method_body_inline)
  return _internal_add_custom_method_body_inline();
}
inline const std::string& MvcRoute::_internal_custom_method_body_inline(int index) const {
  return custom_method_body_inline_.Get(index);
}
inline const std::string& MvcRoute::custom_method_body_inline(int index) const {
  // @@protoc_insertion_point(field_get:aspnet.core.MvcRoute.custom_method_body_inline)
  return _internal_custom_method_body_inline(index);
}
inline std::string* MvcRoute::mutable_custom_method_body_inline(int index) {
  // @@protoc_insertion_point(field_mutable:aspnet.core.MvcRoute.custom_method_body_inline)
  return custom_method_body_inline_.Mutable(index);
}
inline void MvcRoute::set_custom_method_body_inline(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:aspnet.core.MvcRoute.custom_method_body_inline)
  custom_method_body_inline_.Mutable(index)->assign(value);
}
inline void MvcRoute::set_custom_method_body_inline(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:aspnet.core.MvcRoute.custom_method_body_inline)
  custom_method_body_inline_.Mutable(index)->assign(std::move(value));
}
inline void MvcRoute::set_custom_method_body_inline(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  custom_method_body_inline_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:aspnet.core.MvcRoute.custom_method_body_inline)
}
inline void MvcRoute::set_custom_method_body_inline(int index, const char* value, size_t size) {
  custom_method_body_inline_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:aspnet.core.MvcRoute.custom_method_body_inline)
}
inline std::string* MvcRoute::_internal_add_custom_method_body_inline() {
  return custom_method_body_inline_.Add();
}
inline void MvcRoute::add_custom_method_body_inline(const std::string& value) {
  custom_method_body_inline_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:aspnet.core.MvcRoute.custom_method_body_inline)
}
inline void MvcRoute::add_custom_method_body_inline(std::string&& value) {
  custom_method_body_inline_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:aspnet.core.MvcRoute.custom_method_body_inline)
}
inline void MvcRoute::add_custom_method_body_inline(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  custom_method_body_inline_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:aspnet.core.MvcRoute.custom_method_body_inline)
}
inline void MvcRoute::add_custom_method_body_inline(const char* value, size_t size) {
  custom_method_body_inline_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:aspnet.core.MvcRoute.custom_method_body_inline)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
MvcRoute::custom_method_body_inline() const {
  // @@protoc_insertion_point(field_list:aspnet.core.MvcRoute.custom_method_body_inline)
  return custom_method_body_inline_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
MvcRoute::mutable_custom_method_body_inline() {
  // @@protoc_insertion_point(field_mutable_list:aspnet.core.MvcRoute.custom_method_body_inline)
  return &custom_method_body_inline_;
}

// bool is_empty_request = 8;
inline void MvcRoute::clear_is_empty_request() {
  is_empty_request_ = false;
}
inline bool MvcRoute::_internal_is_empty_request() const {
  return is_empty_request_;
}
inline bool MvcRoute::is_empty_request() const {
  // @@protoc_insertion_point(field_get:aspnet.core.MvcRoute.is_empty_request)
  return _internal_is_empty_request();
}
inline void MvcRoute::_internal_set_is_empty_request(bool value) {
  
  is_empty_request_ = value;
}
inline void MvcRoute::set_is_empty_request(bool value) {
  _internal_set_is_empty_request(value);
  // @@protoc_insertion_point(field_set:aspnet.core.MvcRoute.is_empty_request)
}

// repeated string custom_exception_handling = 9;
inline int MvcRoute::_internal_custom_exception_handling_size() const {
  return custom_exception_handling_.size();
}
inline int MvcRoute::custom_exception_handling_size() const {
  return _internal_custom_exception_handling_size();
}
inline void MvcRoute::clear_custom_exception_handling() {
  custom_exception_handling_.Clear();
}
inline std::string* MvcRoute::add_custom_exception_handling() {
  // @@protoc_insertion_point(field_add_mutable:aspnet.core.MvcRoute.custom_exception_handling)
  return _internal_add_custom_exception_handling();
}
inline const std::string& MvcRoute::_internal_custom_exception_handling(int index) const {
  return custom_exception_handling_.Get(index);
}
inline const std::string& MvcRoute::custom_exception_handling(int index) const {
  // @@protoc_insertion_point(field_get:aspnet.core.MvcRoute.custom_exception_handling)
  return _internal_custom_exception_handling(index);
}
inline std::string* MvcRoute::mutable_custom_exception_handling(int index) {
  // @@protoc_insertion_point(field_mutable:aspnet.core.MvcRoute.custom_exception_handling)
  return custom_exception_handling_.Mutable(index);
}
inline void MvcRoute::set_custom_exception_handling(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:aspnet.core.MvcRoute.custom_exception_handling)
  custom_exception_handling_.Mutable(index)->assign(value);
}
inline void MvcRoute::set_custom_exception_handling(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:aspnet.core.MvcRoute.custom_exception_handling)
  custom_exception_handling_.Mutable(index)->assign(std::move(value));
}
inline void MvcRoute::set_custom_exception_handling(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  custom_exception_handling_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:aspnet.core.MvcRoute.custom_exception_handling)
}
inline void MvcRoute::set_custom_exception_handling(int index, const char* value, size_t size) {
  custom_exception_handling_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:aspnet.core.MvcRoute.custom_exception_handling)
}
inline std::string* MvcRoute::_internal_add_custom_exception_handling() {
  return custom_exception_handling_.Add();
}
inline void MvcRoute::add_custom_exception_handling(const std::string& value) {
  custom_exception_handling_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:aspnet.core.MvcRoute.custom_exception_handling)
}
inline void MvcRoute::add_custom_exception_handling(std::string&& value) {
  custom_exception_handling_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:aspnet.core.MvcRoute.custom_exception_handling)
}
inline void MvcRoute::add_custom_exception_handling(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  custom_exception_handling_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:aspnet.core.MvcRoute.custom_exception_handling)
}
inline void MvcRoute::add_custom_exception_handling(const char* value, size_t size) {
  custom_exception_handling_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:aspnet.core.MvcRoute.custom_exception_handling)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
MvcRoute::custom_exception_handling() const {
  // @@protoc_insertion_point(field_list:aspnet.core.MvcRoute.custom_exception_handling)
  return custom_exception_handling_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
MvcRoute::mutable_custom_exception_handling() {
  // @@protoc_insertion_point(field_mutable_list:aspnet.core.MvcRoute.custom_exception_handling)
  return &custom_exception_handling_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace core
}  // namespace aspnet

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::aspnet::core::HttpMethod> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::aspnet::core::HttpMethod>() {
  return ::aspnet::core::HttpMethod_descriptor();
}
template <> struct is_proto_enum< ::aspnet::core::HttpInputSource> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::aspnet::core::HttpInputSource>() {
  return ::aspnet::core::HttpInputSource_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_aspnetcore_2eproto
