// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aspnetcore.proto

#ifndef PROTOBUF_INCLUDED_aspnetcore_2eproto
#define PROTOBUF_INCLUDED_aspnetcore_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/wrappers.pb.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_aspnetcore_2eproto 

namespace protobuf_aspnetcore_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_aspnetcore_2eproto
namespace aspnet {
namespace core {
class MvcRoute;
class MvcRouteDefaultTypeInternal;
extern MvcRouteDefaultTypeInternal _MvcRoute_default_instance_;
}  // namespace core
}  // namespace aspnet
namespace google {
namespace protobuf {
template<> ::aspnet::core::MvcRoute* Arena::CreateMaybeMessage<::aspnet::core::MvcRoute>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace aspnet {
namespace core {

enum HttpMethod {
  HttpMethod_Get = 0,
  HttpMethod_Post = 1,
  HttpMethod_Put = 2,
  HttpMethod_Delete = 3,
  HttpMethod_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  HttpMethod_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool HttpMethod_IsValid(int value);
const HttpMethod HttpMethod_MIN = HttpMethod_Get;
const HttpMethod HttpMethod_MAX = HttpMethod_Delete;
const int HttpMethod_ARRAYSIZE = HttpMethod_MAX + 1;

const ::google::protobuf::EnumDescriptor* HttpMethod_descriptor();
inline const ::std::string& HttpMethod_Name(HttpMethod value) {
  return ::google::protobuf::internal::NameOfEnum(
    HttpMethod_descriptor(), value);
}
inline bool HttpMethod_Parse(
    const ::std::string& name, HttpMethod* value) {
  return ::google::protobuf::internal::ParseNamedEnum<HttpMethod>(
    HttpMethod_descriptor(), name, value);
}
enum HttpInputSource {
  HttpInputSource_Unspecified = 0,
  HttpInputSource_Body = 1,
  HttpInputSource_Form = 2,
  HttpInputSource_Query = 3,
  HttpInputSource_Header = 4,
  HttpInputSource_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  HttpInputSource_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool HttpInputSource_IsValid(int value);
const HttpInputSource HttpInputSource_MIN = HttpInputSource_Unspecified;
const HttpInputSource HttpInputSource_MAX = HttpInputSource_Header;
const int HttpInputSource_ARRAYSIZE = HttpInputSource_MAX + 1;

const ::google::protobuf::EnumDescriptor* HttpInputSource_descriptor();
inline const ::std::string& HttpInputSource_Name(HttpInputSource value) {
  return ::google::protobuf::internal::NameOfEnum(
    HttpInputSource_descriptor(), value);
}
inline bool HttpInputSource_Parse(
    const ::std::string& name, HttpInputSource* value) {
  return ::google::protobuf::internal::ParseNamedEnum<HttpInputSource>(
    HttpInputSource_descriptor(), name, value);
}
// ===================================================================

class MvcRoute : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:aspnet.core.MvcRoute) */ {
 public:
  MvcRoute();
  virtual ~MvcRoute();

  MvcRoute(const MvcRoute& from);

  inline MvcRoute& operator=(const MvcRoute& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MvcRoute(MvcRoute&& from) noexcept
    : MvcRoute() {
    *this = ::std::move(from);
  }

  inline MvcRoute& operator=(MvcRoute&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MvcRoute& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MvcRoute* internal_default_instance() {
    return reinterpret_cast<const MvcRoute*>(
               &_MvcRoute_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(MvcRoute* other);
  friend void swap(MvcRoute& a, MvcRoute& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MvcRoute* New() const final {
    return CreateMaybeMessage<MvcRoute>(NULL);
  }

  MvcRoute* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MvcRoute>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MvcRoute& from);
  void MergeFrom(const MvcRoute& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MvcRoute* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string custom_method_attributes = 4;
  int custom_method_attributes_size() const;
  void clear_custom_method_attributes();
  static const int kCustomMethodAttributesFieldNumber = 4;
  const ::std::string& custom_method_attributes(int index) const;
  ::std::string* mutable_custom_method_attributes(int index);
  void set_custom_method_attributes(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_custom_method_attributes(int index, ::std::string&& value);
  #endif
  void set_custom_method_attributes(int index, const char* value);
  void set_custom_method_attributes(int index, const char* value, size_t size);
  ::std::string* add_custom_method_attributes();
  void add_custom_method_attributes(const ::std::string& value);
  #if LANG_CXX11
  void add_custom_method_attributes(::std::string&& value);
  #endif
  void add_custom_method_attributes(const char* value);
  void add_custom_method_attributes(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& custom_method_attributes() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_custom_method_attributes();

  // repeated string custom_method_body = 6;
  int custom_method_body_size() const;
  void clear_custom_method_body();
  static const int kCustomMethodBodyFieldNumber = 6;
  const ::std::string& custom_method_body(int index) const;
  ::std::string* mutable_custom_method_body(int index);
  void set_custom_method_body(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_custom_method_body(int index, ::std::string&& value);
  #endif
  void set_custom_method_body(int index, const char* value);
  void set_custom_method_body(int index, const char* value, size_t size);
  ::std::string* add_custom_method_body();
  void add_custom_method_body(const ::std::string& value);
  #if LANG_CXX11
  void add_custom_method_body(::std::string&& value);
  #endif
  void add_custom_method_body(const char* value);
  void add_custom_method_body(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& custom_method_body() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_custom_method_body();

  // repeated string custom_exception_handling = 8;
  int custom_exception_handling_size() const;
  void clear_custom_exception_handling();
  static const int kCustomExceptionHandlingFieldNumber = 8;
  const ::std::string& custom_exception_handling(int index) const;
  ::std::string* mutable_custom_exception_handling(int index);
  void set_custom_exception_handling(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_custom_exception_handling(int index, ::std::string&& value);
  #endif
  void set_custom_exception_handling(int index, const char* value);
  void set_custom_exception_handling(int index, const char* value, size_t size);
  ::std::string* add_custom_exception_handling();
  void add_custom_exception_handling(const ::std::string& value);
  #if LANG_CXX11
  void add_custom_exception_handling(::std::string&& value);
  #endif
  void add_custom_exception_handling(const char* value);
  void add_custom_exception_handling(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& custom_exception_handling() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_custom_exception_handling();

  // .google.protobuf.StringValue route_pattern = 3;
  bool has_route_pattern() const;
  void clear_route_pattern();
  static const int kRoutePatternFieldNumber = 3;
  private:
  const ::google::protobuf::StringValue& _internal_route_pattern() const;
  public:
  const ::google::protobuf::StringValue& route_pattern() const;
  ::google::protobuf::StringValue* release_route_pattern();
  ::google::protobuf::StringValue* mutable_route_pattern();
  void set_allocated_route_pattern(::google::protobuf::StringValue* route_pattern);

  // .google.protobuf.StringValue custom_return_type = 5;
  bool has_custom_return_type() const;
  void clear_custom_return_type();
  static const int kCustomReturnTypeFieldNumber = 5;
  private:
  const ::google::protobuf::StringValue& _internal_custom_return_type() const;
  public:
  const ::google::protobuf::StringValue& custom_return_type() const;
  ::google::protobuf::StringValue* release_custom_return_type();
  ::google::protobuf::StringValue* mutable_custom_return_type();
  void set_allocated_custom_return_type(::google::protobuf::StringValue* custom_return_type);

  // .aspnet.core.HttpMethod method = 1;
  void clear_method();
  static const int kMethodFieldNumber = 1;
  ::aspnet::core::HttpMethod method() const;
  void set_method(::aspnet::core::HttpMethod value);

  // .aspnet.core.HttpInputSource source = 2;
  void clear_source();
  static const int kSourceFieldNumber = 2;
  ::aspnet::core::HttpInputSource source() const;
  void set_source(::aspnet::core::HttpInputSource value);

  // bool is_empty_request = 7;
  void clear_is_empty_request();
  static const int kIsEmptyRequestFieldNumber = 7;
  bool is_empty_request() const;
  void set_is_empty_request(bool value);

  // @@protoc_insertion_point(class_scope:aspnet.core.MvcRoute)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> custom_method_attributes_;
  ::google::protobuf::RepeatedPtrField< ::std::string> custom_method_body_;
  ::google::protobuf::RepeatedPtrField< ::std::string> custom_exception_handling_;
  ::google::protobuf::StringValue* route_pattern_;
  ::google::protobuf::StringValue* custom_return_type_;
  int method_;
  int source_;
  bool is_empty_request_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_aspnetcore_2eproto::TableStruct;
};
// ===================================================================

static const int kApiFieldNumber = 25898343;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MethodOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::aspnet::core::MvcRoute >, 11, false >
  api;

// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MvcRoute

// .aspnet.core.HttpMethod method = 1;
inline void MvcRoute::clear_method() {
  method_ = 0;
}
inline ::aspnet::core::HttpMethod MvcRoute::method() const {
  // @@protoc_insertion_point(field_get:aspnet.core.MvcRoute.method)
  return static_cast< ::aspnet::core::HttpMethod >(method_);
}
inline void MvcRoute::set_method(::aspnet::core::HttpMethod value) {
  
  method_ = value;
  // @@protoc_insertion_point(field_set:aspnet.core.MvcRoute.method)
}

// .aspnet.core.HttpInputSource source = 2;
inline void MvcRoute::clear_source() {
  source_ = 0;
}
inline ::aspnet::core::HttpInputSource MvcRoute::source() const {
  // @@protoc_insertion_point(field_get:aspnet.core.MvcRoute.source)
  return static_cast< ::aspnet::core::HttpInputSource >(source_);
}
inline void MvcRoute::set_source(::aspnet::core::HttpInputSource value) {
  
  source_ = value;
  // @@protoc_insertion_point(field_set:aspnet.core.MvcRoute.source)
}

// .google.protobuf.StringValue route_pattern = 3;
inline bool MvcRoute::has_route_pattern() const {
  return this != internal_default_instance() && route_pattern_ != NULL;
}
inline const ::google::protobuf::StringValue& MvcRoute::_internal_route_pattern() const {
  return *route_pattern_;
}
inline const ::google::protobuf::StringValue& MvcRoute::route_pattern() const {
  const ::google::protobuf::StringValue* p = route_pattern_;
  // @@protoc_insertion_point(field_get:aspnet.core.MvcRoute.route_pattern)
  return p != NULL ? *p : *reinterpret_cast<const ::google::protobuf::StringValue*>(
      &::google::protobuf::_StringValue_default_instance_);
}
inline ::google::protobuf::StringValue* MvcRoute::release_route_pattern() {
  // @@protoc_insertion_point(field_release:aspnet.core.MvcRoute.route_pattern)
  
  ::google::protobuf::StringValue* temp = route_pattern_;
  route_pattern_ = NULL;
  return temp;
}
inline ::google::protobuf::StringValue* MvcRoute::mutable_route_pattern() {
  
  if (route_pattern_ == NULL) {
    auto* p = CreateMaybeMessage<::google::protobuf::StringValue>(GetArenaNoVirtual());
    route_pattern_ = p;
  }
  // @@protoc_insertion_point(field_mutable:aspnet.core.MvcRoute.route_pattern)
  return route_pattern_;
}
inline void MvcRoute::set_allocated_route_pattern(::google::protobuf::StringValue* route_pattern) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(route_pattern_);
  }
  if (route_pattern) {
    ::google::protobuf::Arena* submessage_arena =
      reinterpret_cast<::google::protobuf::MessageLite*>(route_pattern)->GetArena();
    if (message_arena != submessage_arena) {
      route_pattern = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, route_pattern, submessage_arena);
    }
    
  } else {
    
  }
  route_pattern_ = route_pattern;
  // @@protoc_insertion_point(field_set_allocated:aspnet.core.MvcRoute.route_pattern)
}

// repeated string custom_method_attributes = 4;
inline int MvcRoute::custom_method_attributes_size() const {
  return custom_method_attributes_.size();
}
inline void MvcRoute::clear_custom_method_attributes() {
  custom_method_attributes_.Clear();
}
inline const ::std::string& MvcRoute::custom_method_attributes(int index) const {
  // @@protoc_insertion_point(field_get:aspnet.core.MvcRoute.custom_method_attributes)
  return custom_method_attributes_.Get(index);
}
inline ::std::string* MvcRoute::mutable_custom_method_attributes(int index) {
  // @@protoc_insertion_point(field_mutable:aspnet.core.MvcRoute.custom_method_attributes)
  return custom_method_attributes_.Mutable(index);
}
inline void MvcRoute::set_custom_method_attributes(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:aspnet.core.MvcRoute.custom_method_attributes)
  custom_method_attributes_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void MvcRoute::set_custom_method_attributes(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:aspnet.core.MvcRoute.custom_method_attributes)
  custom_method_attributes_.Mutable(index)->assign(std::move(value));
}
#endif
inline void MvcRoute::set_custom_method_attributes(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  custom_method_attributes_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:aspnet.core.MvcRoute.custom_method_attributes)
}
inline void MvcRoute::set_custom_method_attributes(int index, const char* value, size_t size) {
  custom_method_attributes_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:aspnet.core.MvcRoute.custom_method_attributes)
}
inline ::std::string* MvcRoute::add_custom_method_attributes() {
  // @@protoc_insertion_point(field_add_mutable:aspnet.core.MvcRoute.custom_method_attributes)
  return custom_method_attributes_.Add();
}
inline void MvcRoute::add_custom_method_attributes(const ::std::string& value) {
  custom_method_attributes_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:aspnet.core.MvcRoute.custom_method_attributes)
}
#if LANG_CXX11
inline void MvcRoute::add_custom_method_attributes(::std::string&& value) {
  custom_method_attributes_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:aspnet.core.MvcRoute.custom_method_attributes)
}
#endif
inline void MvcRoute::add_custom_method_attributes(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  custom_method_attributes_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:aspnet.core.MvcRoute.custom_method_attributes)
}
inline void MvcRoute::add_custom_method_attributes(const char* value, size_t size) {
  custom_method_attributes_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:aspnet.core.MvcRoute.custom_method_attributes)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
MvcRoute::custom_method_attributes() const {
  // @@protoc_insertion_point(field_list:aspnet.core.MvcRoute.custom_method_attributes)
  return custom_method_attributes_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
MvcRoute::mutable_custom_method_attributes() {
  // @@protoc_insertion_point(field_mutable_list:aspnet.core.MvcRoute.custom_method_attributes)
  return &custom_method_attributes_;
}

// .google.protobuf.StringValue custom_return_type = 5;
inline bool MvcRoute::has_custom_return_type() const {
  return this != internal_default_instance() && custom_return_type_ != NULL;
}
inline const ::google::protobuf::StringValue& MvcRoute::_internal_custom_return_type() const {
  return *custom_return_type_;
}
inline const ::google::protobuf::StringValue& MvcRoute::custom_return_type() const {
  const ::google::protobuf::StringValue* p = custom_return_type_;
  // @@protoc_insertion_point(field_get:aspnet.core.MvcRoute.custom_return_type)
  return p != NULL ? *p : *reinterpret_cast<const ::google::protobuf::StringValue*>(
      &::google::protobuf::_StringValue_default_instance_);
}
inline ::google::protobuf::StringValue* MvcRoute::release_custom_return_type() {
  // @@protoc_insertion_point(field_release:aspnet.core.MvcRoute.custom_return_type)
  
  ::google::protobuf::StringValue* temp = custom_return_type_;
  custom_return_type_ = NULL;
  return temp;
}
inline ::google::protobuf::StringValue* MvcRoute::mutable_custom_return_type() {
  
  if (custom_return_type_ == NULL) {
    auto* p = CreateMaybeMessage<::google::protobuf::StringValue>(GetArenaNoVirtual());
    custom_return_type_ = p;
  }
  // @@protoc_insertion_point(field_mutable:aspnet.core.MvcRoute.custom_return_type)
  return custom_return_type_;
}
inline void MvcRoute::set_allocated_custom_return_type(::google::protobuf::StringValue* custom_return_type) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(custom_return_type_);
  }
  if (custom_return_type) {
    ::google::protobuf::Arena* submessage_arena =
      reinterpret_cast<::google::protobuf::MessageLite*>(custom_return_type)->GetArena();
    if (message_arena != submessage_arena) {
      custom_return_type = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, custom_return_type, submessage_arena);
    }
    
  } else {
    
  }
  custom_return_type_ = custom_return_type;
  // @@protoc_insertion_point(field_set_allocated:aspnet.core.MvcRoute.custom_return_type)
}

// repeated string custom_method_body = 6;
inline int MvcRoute::custom_method_body_size() const {
  return custom_method_body_.size();
}
inline void MvcRoute::clear_custom_method_body() {
  custom_method_body_.Clear();
}
inline const ::std::string& MvcRoute::custom_method_body(int index) const {
  // @@protoc_insertion_point(field_get:aspnet.core.MvcRoute.custom_method_body)
  return custom_method_body_.Get(index);
}
inline ::std::string* MvcRoute::mutable_custom_method_body(int index) {
  // @@protoc_insertion_point(field_mutable:aspnet.core.MvcRoute.custom_method_body)
  return custom_method_body_.Mutable(index);
}
inline void MvcRoute::set_custom_method_body(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:aspnet.core.MvcRoute.custom_method_body)
  custom_method_body_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void MvcRoute::set_custom_method_body(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:aspnet.core.MvcRoute.custom_method_body)
  custom_method_body_.Mutable(index)->assign(std::move(value));
}
#endif
inline void MvcRoute::set_custom_method_body(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  custom_method_body_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:aspnet.core.MvcRoute.custom_method_body)
}
inline void MvcRoute::set_custom_method_body(int index, const char* value, size_t size) {
  custom_method_body_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:aspnet.core.MvcRoute.custom_method_body)
}
inline ::std::string* MvcRoute::add_custom_method_body() {
  // @@protoc_insertion_point(field_add_mutable:aspnet.core.MvcRoute.custom_method_body)
  return custom_method_body_.Add();
}
inline void MvcRoute::add_custom_method_body(const ::std::string& value) {
  custom_method_body_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:aspnet.core.MvcRoute.custom_method_body)
}
#if LANG_CXX11
inline void MvcRoute::add_custom_method_body(::std::string&& value) {
  custom_method_body_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:aspnet.core.MvcRoute.custom_method_body)
}
#endif
inline void MvcRoute::add_custom_method_body(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  custom_method_body_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:aspnet.core.MvcRoute.custom_method_body)
}
inline void MvcRoute::add_custom_method_body(const char* value, size_t size) {
  custom_method_body_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:aspnet.core.MvcRoute.custom_method_body)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
MvcRoute::custom_method_body() const {
  // @@protoc_insertion_point(field_list:aspnet.core.MvcRoute.custom_method_body)
  return custom_method_body_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
MvcRoute::mutable_custom_method_body() {
  // @@protoc_insertion_point(field_mutable_list:aspnet.core.MvcRoute.custom_method_body)
  return &custom_method_body_;
}

// bool is_empty_request = 7;
inline void MvcRoute::clear_is_empty_request() {
  is_empty_request_ = false;
}
inline bool MvcRoute::is_empty_request() const {
  // @@protoc_insertion_point(field_get:aspnet.core.MvcRoute.is_empty_request)
  return is_empty_request_;
}
inline void MvcRoute::set_is_empty_request(bool value) {
  
  is_empty_request_ = value;
  // @@protoc_insertion_point(field_set:aspnet.core.MvcRoute.is_empty_request)
}

// repeated string custom_exception_handling = 8;
inline int MvcRoute::custom_exception_handling_size() const {
  return custom_exception_handling_.size();
}
inline void MvcRoute::clear_custom_exception_handling() {
  custom_exception_handling_.Clear();
}
inline const ::std::string& MvcRoute::custom_exception_handling(int index) const {
  // @@protoc_insertion_point(field_get:aspnet.core.MvcRoute.custom_exception_handling)
  return custom_exception_handling_.Get(index);
}
inline ::std::string* MvcRoute::mutable_custom_exception_handling(int index) {
  // @@protoc_insertion_point(field_mutable:aspnet.core.MvcRoute.custom_exception_handling)
  return custom_exception_handling_.Mutable(index);
}
inline void MvcRoute::set_custom_exception_handling(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:aspnet.core.MvcRoute.custom_exception_handling)
  custom_exception_handling_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void MvcRoute::set_custom_exception_handling(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:aspnet.core.MvcRoute.custom_exception_handling)
  custom_exception_handling_.Mutable(index)->assign(std::move(value));
}
#endif
inline void MvcRoute::set_custom_exception_handling(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  custom_exception_handling_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:aspnet.core.MvcRoute.custom_exception_handling)
}
inline void MvcRoute::set_custom_exception_handling(int index, const char* value, size_t size) {
  custom_exception_handling_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:aspnet.core.MvcRoute.custom_exception_handling)
}
inline ::std::string* MvcRoute::add_custom_exception_handling() {
  // @@protoc_insertion_point(field_add_mutable:aspnet.core.MvcRoute.custom_exception_handling)
  return custom_exception_handling_.Add();
}
inline void MvcRoute::add_custom_exception_handling(const ::std::string& value) {
  custom_exception_handling_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:aspnet.core.MvcRoute.custom_exception_handling)
}
#if LANG_CXX11
inline void MvcRoute::add_custom_exception_handling(::std::string&& value) {
  custom_exception_handling_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:aspnet.core.MvcRoute.custom_exception_handling)
}
#endif
inline void MvcRoute::add_custom_exception_handling(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  custom_exception_handling_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:aspnet.core.MvcRoute.custom_exception_handling)
}
inline void MvcRoute::add_custom_exception_handling(const char* value, size_t size) {
  custom_exception_handling_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:aspnet.core.MvcRoute.custom_exception_handling)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
MvcRoute::custom_exception_handling() const {
  // @@protoc_insertion_point(field_list:aspnet.core.MvcRoute.custom_exception_handling)
  return custom_exception_handling_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
MvcRoute::mutable_custom_exception_handling() {
  // @@protoc_insertion_point(field_mutable_list:aspnet.core.MvcRoute.custom_exception_handling)
  return &custom_exception_handling_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace core
}  // namespace aspnet

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::aspnet::core::HttpMethod> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::aspnet::core::HttpMethod>() {
  return ::aspnet::core::HttpMethod_descriptor();
}
template <> struct is_proto_enum< ::aspnet::core::HttpInputSource> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::aspnet::core::HttpInputSource>() {
  return ::aspnet::core::HttpInputSource_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_aspnetcore_2eproto
